config/routes.rb
Rails.application.routes.draw do


  resources :restaurants



  # # List all restaurants
  # get 'restaurants', to: 'restaurants#index'

  # # show create form
  # get 'restaurants/new', to: 'restaurants#new'

  # # List one restaurant
  # get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  # # create the restaurant
  # post 'restaurants', to: 'restaurants#create'

  # # show edit form
  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'

  # # update the restaurant
  # patch 'restaurants/:id', to: 'restaurants#update'

  # # delete the restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for restaurant do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :stars %>
  <%= f.text_field :stars %>

  <%= f.submit %>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit new Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant)  %></li>
  <% end %>
</ul>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create new Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>Info of Restaurant</h1>

<p>Name: <%= @restaurant.name %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Stars: <%= @restaurant.stars %></p>


<p>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
</p>

<p>
<%= link_to 'Remove this Restaurant', restaurant_path, method: :delete %>
</p>